# Generated by Django 4.0.4 on 2022-04-17 09:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reviews',
            options={'verbose_name': 'request', 'verbose_name_plural': 'requests'},
        ),
        migrations.AddField(
            model_name='reviews',
            name='stars',
            field=models.PositiveSmallIntegerField(default=25, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Stars'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reviews',
            name='task',
            field=models.TextField(verbose_name='Reviews'),
        ),
    ]
