# Generated by Django 4.0.4 on 2022-04-18 18:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_reviews_valid_stars_range'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='user',
            field=models.CharField(default=django.utils.timezone.now, max_length=15, verbose_name='User'),
            preserve_default=False,
        ),
    ]
