# Generated by Django 4.2.dev20220902080224 on 2023-04-15 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_favorite_for_product_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Favorite_For_Product',
        ),
    ]
