# Generated by Django 4.2.dev20220902080224 on 2023-04-16 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_delete_favorite_for_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorite',
            name='yields',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.yield'),
            preserve_default=False,
        ),
    ]
