# Generated by Django 4.2.dev20220902080224 on 2023-04-17 06:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0009_alter_favorite_product_alter_favorite_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pnumber', models.PositiveBigIntegerField(verbose_name='Phone number')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('yields', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.yield')),
            ],
        ),
    ]
