# Generated by Django 4.2.dev20220902080224 on 2023-04-17 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='adress',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
