# Generated by Django 4.2.dev20220902080224 on 2023-04-26 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_avatar'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Avatar',
        ),
    ]
