# Generated by Django 4.2.dev20220902080224 on 2023-04-27 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_profile_of_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile_of_user',
            name='avatar',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to='avatars/'),
        ),
        migrations.AlterField(
            model_name='profile_of_user',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
