# Generated by Django 4.2.dev20220902080224 on 2023-07-04 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_rename_image_product_image_1_product_image_2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='yield',
            old_name='image',
            new_name='image_1',
        ),
        migrations.AddField(
            model_name='yield',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
        migrations.AddField(
            model_name='yield',
            name='image_3',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
        migrations.AddField(
            model_name='yield',
            name='image_4',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
        migrations.AddField(
            model_name='yield',
            name='image_5',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
        migrations.AddField(
            model_name='yield',
            name='image_6',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
    ]
